parameters:
    extensions_archiver_step.step.archiver.class: Extensions\Bundle\ArchiverStepBundle\Step\ArchiverStep

services:
    extensions_archiver_step.step.archiver:
        class: '%extensions_archiver_step.step.archiver.class%'
        arguments:
            - 'archiver'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
