extensions:
    pim-job-instance-csv-product-import-archiver-edit:
        module: pim/form/common/edit-form
    
    pim-job-instance-csv-product-import-archiver-edit-main-image:
        module: pim/form/common/main-image
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: main-image
        config:
            path: bundles/extensionsarchiverstep/images/ArchiverStep_mini.jpg

    pim-job-instance-csv-product-import-archiver-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-job-instance-csv-product-import-archiver-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pim-job-instance-csv-product-import-archiver-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-csv-product-import-archiver-edit
        position: 1000

    pim-job-instance-csv-product-import-archiver-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: content
        position: 100

    pim-job-instance-csv-product-import-archiver-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-csv-product-import-archiver-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_common.properties
            tabCode: pim-job-instance-properties

    pim-job-instance-csv-product-import-archiver-edit-global:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-csv-product-import-archiver-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode: pim-job-instance-global

    pim-job-instance-csv-product-import-archiver-edit-history:
        module: pim/common/tab/history
        parent: pim-job-instance-csv-product-import-archiver-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 130
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_common.history
            tabCode: pim-job-instance-history

    pim-job-instance-csv-product-import-archiver-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_common.code
            readOnly: true

    pim-job-instance-csv-product-import-archiver-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_common.label

    pim-job-instance-csv-product-import-archiver-edit-properties-file-path:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 120
        targetZone: properties
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.file_path.title
            tooltip: pim_import_export.form.job_instance.tab.properties.file_path.help

    pim-job-instance-csv-product-import-archiver-edit-properties-archiver-enabled:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 125
        targetZone: properties
        config:
            fieldCode: configuration.archiverEnabled
            readOnly: false
            label: archiver.form.job_instance.tab.properties.archiverEnabled.title
            tooltip: archiver.form.job_instance.tab.properties.archiverEnabled.help

    pim-job-instance-csv-product-import-archiver-edit-properties-dir-archive:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.dirArchive
            readOnly: false
            label: archiver.form.job_instance.tab.properties.dir_archive.title
            tooltip: archiver.form.job_instance.tab.properties.dir_archive.help

    pim-job-instance-csv-product-import-archiver-edit-properties-file-upload:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 150
        targetZone: properties
        config:
            fieldCode: configuration.uploadAllowed
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.upload_allowed.title
            tooltip: pim_import_export.form.job_instance.tab.properties.upload_allowed.help
            readOnly: false

    pim-job-instance-csv-product-import-archiver-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 160
        targetZone: properties
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_import_export.form.job_instance.tab.properties.delimiter.help

    pim-job-instance-csv-product-import-archiver-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 170
        targetZone: properties
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_import_export.form.job_instance.tab.properties.enclosure.help

    pim-job-instance-csv-product-import-archiver-edit-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 180
        targetZone: properties
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_import_export.form.job_instance.tab.properties.decimal_separator.help

    pim-job-instance-csv-product-import-archiver-edit-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 190
        targetZone: properties
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.date_format.title
            tooltip: pim_import_export.form.job_instance.tab.properties.date_format.help

    pim-job-instance-csv-product-import-archiver-edit-properties-enabled:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 200
        targetZone: properties
        config:
            fieldCode: configuration.enabled
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.enabled.title
            tooltip: pim_import_export.form.job_instance.tab.properties.enabled.help

    pim-job-instance-csv-product-import-archiver-edit-properties-categories-column:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 210
        targetZone: properties
        config:
            fieldCode: configuration.categoriesColumn
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.categories_column.title
            tooltip: pim_import_export.form.job_instance.tab.properties.categories_column.help

    pim-job-instance-csv-product-import-archiver-edit-properties-family-column:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 220
        targetZone: properties
        config:
            fieldCode: configuration.familyColumn
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.family_column.title
            tooltip: pim_import_export.form.job_instance.tab.properties.family_column.help

    pim-job-instance-csv-product-import-archiver-edit-properties-groups-column:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 230
        targetZone: properties
        config:
            fieldCode: configuration.groupsColumn
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.groups_column.title
            tooltip: pim_import_export.form.job_instance.tab.properties.groups_column.help

    pim-job-instance-csv-product-import-archiver-edit-properties-enabled-comparison:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 240
        targetZone: properties
        config:
            fieldCode: configuration.enabledComparison
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.enabled_comparison.title
            tooltip: pim_import_export.form.job_instance.tab.properties.enabled_comparison.help

    pim-job-instance-csv-product-import-archiver-edit-properties-real-time-versioning:
        module: pim/job/common/edit/field/switch
        parent: pim-job-instance-csv-product-import-archiver-edit-global
        position: 250
        targetZone: properties
        config:
            fieldCode: configuration.realTimeVersioning
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.real_time_versioning.title
            tooltip: pim_import_export.form.job_instance.tab.properties.real_time_versioning.help

    pim-job-instance-csv-product-import-archiver-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: title
        position: 100

    pim-job-instance-csv-product-import-archiver-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: meta
        position: 100

    pim-job-instance-csv-product-import-archiver-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: buttons
        position: 50

    pim-job-instance-csv-product-import-archiver-edit-delete:
        module: pim/job/import/edit/delete
        parent: pim-job-instance-csv-product-import-archiver-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.import_profile
                content: pim_common.confirm_deletion
                success: pim_import_export.entity.job_instance.flash.delete.success
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    pim-job-instance-csv-product-import-archiver-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: buttons
        position: 120

    pim-job-instance-csv-product-import-archiver-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    pim-job-instance-csv-product-import-archiver-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-csv-product-import-archiver-edit
        targetZone: state
        position: 900
        config:
            entity: pim_import_export.entity.job_instance.label

    pim-job-instance-csv-product-import-archiver-edit-validation:
        module: pim/job/common/edit/validation
        parent: pim-job-instance-csv-product-import-archiver-edit
